# Generated by Django 5.2.4 on 2025-07-16 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="allergies",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="reservation",
            name="purpose",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="reservation",
            name="requests",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="reservation",
            name="status",
            field=models.CharField(default="pending", max_length=20),
        ),
    ]
