# Generated by Django 5.2.4 on 2025-07-17 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_reservation_allergies_reservation_purpose_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="paid",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="reservation",
            name="paymongo_session_id",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("confirmed", "Confirmed"),
                    ("cancelled", "Cancelled"),
                    ("no_show", "No‑Show"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
