# Generated by Django 5.2.4 on 2025-07-18 06:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_reservation_paid_reservation_paymongo_session_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='cancel_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='table',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='WaitlistEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('guest_total', models.PositiveIntegerField()),
                ('preferred_time', models.TimeField()),
                ('date', models.DateField()),
                ('purpose', models.CharField(blank=True, max_length=100)),
                ('allergies', models.TextField(blank=True)),
                ('requests', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.branch')),
            ],
        ),
    ]
